### ISSUE TITLE
Playtesting Feedback: James Watt

### ISSUE THREAD

**Issue by Fellarg** [Nickel64/Singularity-Group-Project#17]
Name: James. Watt

I found the single open world level to easy to explore and a fun environment to navigate but an environment with no orientation or restriction. I found it hard to establish my position in the map, there was no major structure that i could orientate myself with and the map edges were unclear. This directionless coupled with the very sharp turning dynamics of the rocket made the game a somewhat disorientating experience.

**Comment by nsHeresy** [comment]
To improve the player's orientation in the game level, there are several changes that the team has proposed. Firstly, including some form of minimap (#23) should give the player a better sense of their direction and position within the level. Also, the player's interaction with the map edges will be changed. The options for this were to either increase the size of the level, or to change the interaction so that the player isn't destroyed when they go outside level bounds. We have decided to modify the interaction, so that the player will be teleported (via wormhole) to the opposite side of the level (#24). This should help to improve the orientation issues James was experiencing 👍

**Comment by b-ran** [comment]
Feedback issues completed, closing
