### ISSUE TITLE
Playtesting Feedback: Danielle Allen

### ISSUE THREAD

**Issue by nsHeresy** [Nickel64/Singularity-Group-Project#19]
Name: Danielle Allen	allendani1

Some tutorial or instructions would be good, including controls and the aim of the game. Other information such as ship health and perhaps how many shots you have - unless it is unlimited. The graphics were really cool, but what to do or how to do it was unclear. Hard to tell what is background graphics and what I can interact with.

**Comment by nsHeresy** [comment]
For providing instructions/tutorials for the game, we could either create a tutorial level/sequence, or provide the player with instructions/controls within a menu. We decided to go with the latter option (#26), as this will allow the player to review controls at any point during gameplay. The build that Danielle played on did not have a HUD, this has already been identified as an issue for the project (#30).
In terms of showing the player objectives, the current objective/wave count/enemies left will be added to the overlay ui (#37).
Since the playtest, some of the background items have been baked into the scenery, so the distinction between background and level objects is a bit clearer now.

**Comment by Fellarg** [comment]
Tutorial information could be as simple as one screen available in the main menu showing controls and with a simple rundown of game objectives, although a simplified version in the in game pause menu would be great to act as a quick reference. Currently the game does have issues with communicating information regarding objective and ship stats to the player, but we aim to fix that with issues #30, #31 and #32. Separation between level and background has been improved since play testing, with asteroids being pushed into a ring surrounding the map rather than being a part of it.

**Comment by nsHeresy** [comment]
Ship health and tutorial have been implemented #30 #43
