### ISSUE TITLE
Playtesting Feedback: Karu Skipper

### ISSUE THREAD

**Issue by nsHeresy** [Nickel64/Singularity-Group-Project#21]
Name: Karu Skipper
Work on an objective for the player, have an objective text in the corner and maybe a count of remaining enemy ships. I found myself just flying around with no purpose and didnt realise I was dead. Make sure to add some sort of death whether its an explosion or a reset to the start.

**Comment by b-ran** [comment]
Karu was playing on build that had no working shooting system and boundary system half kills the player (just removes the model #28) . There issue with not feeling like there was much purpose was valid, so on top actually having a shooting system and reward system of giving the player points as the kill ships was decided on; Instead of having count remaining like Karu suggested to keep with the arcade feel.  During the play test Karu went into the game world boundary encountering the bug #28 of player not be killed, we chosen to instead punishing the player for going out of bounds by killing them to add secret wormhole machine teleporting them to the other side of the game world #24

**Comment by nsHeresy** [comment]
Player death is now very obvious, and immediately presents with a game over screen
