### ISSUE TITLE
Playtesting Feedback: Patrick Lynch

### ISSUE THREAD

**Issue by nsHeresy** [Nickel64/Singularity-Group-Project#22]
Name: Patrick Lynch (lynchpatr1)
Game world is much too small, and model disappears when player leaves it
Give them a warning as they leave the game world (e.g. X seconds to return to battle)
Have the ship destroyed when it leaves the area for too long
Movement is slightly sluggish, not quite satisfactory enough
Still have it lag behind mouse movement (can’t be too sensitive), but make it a little bit more snappy
Need to have collisions with objects, have ship get destroyed
Targeting reticule needs to disappear when not being used, needs to look prettier
The main crosshairs looks a little blurry/pixelated, but futuristic look is cool. Just needs to look more crisp.
Collide with and be able to shoot apart meteors, make them move slightly and rotate
Fix the missiles not going where expected, give them a cool model and trail effect
Add some enemies! :)

**Comment by Fellarg** [comment]
During play testing, there was a large, spinning space station placed in the scene in front of he player's spawn, this caused players to head straight for the station which was unfortunately half outside of the boundary. as a result the world felt small since the player flew straight out of the map. deleting the ship once they exit the boundary is an issue being addressed in issues #28 and #24. Movement could be sped up a little by increasing mouse sensitivity, and option to set this in the menu would allow this to be set to each player's preference. Collisions seemed like the biggest problem in the play test version of the game, but with the addition of enemies, damage on collision may be too difficult for low skill players. collision behavior does need to be changed to avoid the player becoming stuck. Having the target icon disappear would be reasonable for a game with more downtime, but we a aiming for a more arcady feel where downtime should be avoided. Crosshair doesn't seem to be an issue, just wasn't a lot happening on the screen so it became the focus. shooting apart meteors is way out of scope, we aim for them to be background rather than a main focus. Missiles were brand new as of playtesting and needed work. enemies have been added ! :)

**Comment by b-ran** [comment]
Feedback issue completed, closing
